version: '3.7'

services:
  rabbit-mq:
    container_name: rabbit-mq
    image: rabbitmq:3.6-management-alpine
    ports:
      # The standard AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    networks:
      - go-network

networks:
  go-network:
    driver: bridge
