version: '3.7'

services:
  go-rabbit-mq:
    container_name: go-rabbit-mq
    image: rabbitmq:3.6-management-alpine
    ports:
      # The standard AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    volumes:
      - rabitmq:/etc/rabbitmq/
    networks:
      - go-network

  go-mongodb:
    image: mongo
    container_name: go-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - go-network

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:
  rabitmq:

networks:
  go-network:
    driver: bridge